### ISSUE TITLE
New REPL: `python -q` outputs unnecessary blank space on empty terminal

### ISSUE THREAD

**Issue by jfly** [python/cpython#131743]
# Bug report

### Bug description:

If I start the new REPL on a clear terminal, I get an unnecessary blank space.

```python
clear; python -q
```

![Image](https://github.com/user-attachments/assets/734317f0-ae5d-4b69-a009-5ea0840b887d)

Whereas this does not happen if I run the old ("basic") REPL:

```python
clear; PYTHON_BASIC_REPL=1 python -q
```
![Image](https://github.com/user-attachments/assets/14b43ce5-925e-4d16-b1ca-dea262c5b33c)

### Analysis

I've tracked this down to these 2 lines of code: https://github.com/python/cpython/blob/3.13/Lib/_pyrepl/unix_console.py#L241-L242

```python
self.__move(0, len(self.screen) - 1)
self.__write("\n")
```

I don't totally understand this code, but it certainly smells like there's a bug here when dealing with an empty screen (for example, if `len(self.screen) == 0`, are we trying to move the cursor to index `-1`?)

I'm not sure what the fix is here, though. I don't really understand this code: why are we moving up to a line just to move the cursor down a line afterwards? why can't we jump straight to where we want to be? I tried digging through the git history for answers, but it looks like this incantation dates back all the way to [this initial commit to pypi/pyrepl](https://github.com/pypy/pyrepl/commit/04c411e080fcd696499fe62cee299c258e74220a). I'm not sure how to dig any further back in time.

### CPython versions tested on:

3.13, 3.14, CPython main branch

### Operating systems tested on:

Linux

I'm using Alacritty, in case that's relevant.

### Linked PRs
* gh-131907

**Comment by skirpichev** [comment]
> I'm using Alacritty, in case that's relevant.

I think so.  I can't reproduce this in gterm.

**Comment by jfly** [comment]
@skirpichev, what is gterm? Is it `gnome-terminal`? I am able to reproduce the issue with `gnome-terminal`.

**Comment by skirpichev** [comment]
> I am able to reproduce the issue with gnome-terminal.

Hmm, my fault.  It's important to run commands as one-liner's, i.e. `clear;./python -q`.

**Comment by donBarbos** [comment]
this is also reproduced on my system. i use `kitty`

**Comment by donBarbos** [comment]
it seems that these actions are not needed in some cases, so if we do this inside block `if len(self.screen):` the problem is not reproduced and the tests still pass (at least for me)

we also have same code in [`WondowsConsole.refresh`](https://github.com/python/cpython/blob/main/Lib/_pyrepl/windows_console.py#L173-L174) method, i think we should fix that too

if no one minds i'll send PR, and it would be nice to make backport for 3.13

**Comment by jfly** [comment]
That sounds like a safe change to me, @donBarbos.

I'm curious though: can you explain why we *ever* need to do this? Why are we jumping 1 line above where we need to go just to go one 1 down right after? Why are we even jumping the cursor around at all? (I don't think we're redrawing the entire screen, are we?)

**Comment by donBarbos** [comment]
for example when we want to move to the next line after entering `:` for some construction

but I'm not an expert :-) it's better to ask the author or some of core team

**Comment by jfly** [comment]
> for example when we want to move to the next line after entering : for some construction

I still don't understand why we wouldn't jump straight to where we want to go. Why one above and then down?

**Comment by donBarbos** [comment]
cc @pablogsal as author of new python repl

sorry for ping, do you mind?

**Comment by StanFromIreland** [comment]
Possibly also causing this behavior:

```
$ ./python
Python 3.14.0a7+ (heads/main-dirty:1e5798e3725, Apr 13 2025, 08:52:57) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[1]+  Stopped                 ./python
$ fg
./python
test
>>> test
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    test
NameError: name 'test' is not defined
>>> 
```

**Comment by jfly** [comment]
Sorry, what are you showing here, @StanFromIreland?

**Comment by StanFromIreland** [comment]
Input starts on a **_blank line_** and is duplicated on enter.
