### ISSUE TITLE
test_local.TestEnUSCollection failures on Solaris 10

### ISSUE THREAD

**Issue by tpn** [python/cpython#60462]
BPO | [16258](https://bugs.python.org/issue16258)
--- | :---
Nosy | @loewis, @jcea, @vstinner, @tpn, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-10-17.02:19:55.577>
labels = ['extension-modules', 'type-bug', '3.7']
title = 'test_local.TestEnUSCollection failures on Solaris 10'
updated_at = <Date 2017-06-20.14:54:41.733>
user = 'https://github.com/tpn'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-20.14:54:41.733>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2012-10-17.02:19:55.577>
creator = 'trent'
dependencies = []
files = []
hgrepos = []
issue_num = 16258
keywords = ['3.3regression']
message_count = 17.0
messages = ['173124', '173164', '173166', '173167', '173168', '173171', '173172', '173199', '289382', '296414', '296415', '296416', '296418', '296435', '296440', '296441', '296445']
nosy_count = 6.0
nosy_names = ['loewis', 'jcea', 'vstinner', 'trent', 'serhiy.storchaka', 'petriborg']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16258'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
May be bpo-15954 is related to this issue. Is this issue still reproduced?

**Comment by 0a8138bd-e4ab-4a36-b81e-9117d13194bd** [comment]
I'm getting the same 2 errors in Python 3.4.6 on Solaris 11.

Comes up when you run 'gmake test' or

./python -W default -bb -E -W error::BytesWarning -m test -r -w -j 0 -v test_locale.py

**Comment by vstinner** [comment]
A solution for that would be to return the raw byte string or to return a list of integers, rather than an unicode string.

I don't think that locale.strxfrm() result is supposed to be displayed in a terminal, it should only be used to sort two strings, or to be used as a key function for list.sort() for example.

**Comment by vstinner** [comment]
Currently, the function is documented to return a string:
https://docs.python.org/dev/library/locale.html#locale.strxfrm
"Transforms a string to one that can be used in locale-aware comparisons."

The problem is that we don't have enough developers who care of Solaris/Illimios to fix these issues (propose patches).

test_locale is just \*one* example. The curses module is broken for years on Solaris if I recall correctly...

**Comment by serhiy-storchaka** [comment]
It is possible to use the special "encoding" for transformed strings on platforms with broken wcsxfrm().

All codes \< 0x10000 are not changed. Codes \>= 0x10000 are encoded as a pair: 0x10000 + (code \>\> 16), code & 0xffff.

**Comment by vstinner** [comment]
> It is possible to use the special "encoding" for transformed strings on platforms with broken wcsxfrm().

I wouldn't say that the function is wrong. wchar_t is 32-bit long, the
function is free to use numbers \> 0x10ffff. It's more a Python
limitation, no?

**Comment by serhiy-storchaka** [comment]
Agree, it's more a Python limitation.

**Comment by vstinner** [comment]
> Agree, it's more a Python limitation.

Why do you think of changing locale.strxfrm() from str to bytes or tuple? I prefer a tuple.

But again, I'm not super motivated by this change. IMHO there are more severe issues that should be fixed in Solaris.

**Comment by serhiy-storchaka** [comment]
This will change the documented behavior. Even if allow this change in a new feature release, it can't be made in maintained releases.

A tuple of integers is memory excessive and slow. A bytes object is more compact (but may be less compact than a string) and faster. But on little-endian platform every wchar_t should be converted to big-endian for supporting comparison of bytes objects.

**Comment by vstinner** [comment]
This issue was fixed in Python 3.10 by @kulikjak with the commit 9032cf5cb1e33c0349089cfb0f6bf11ed3c30e86.

**Comment by serhiy-storchaka** [comment]
Cool!

**Comment by kulikjak** [comment]
I did one more digging into this, and sadly, considering the current implementation, it never will (and it is really a different issue from 9032cf5cb1e33c0349089cfb0f6bf11ed3c30e86 as this isn't about unicode/non-unicode `wchar_t` representation.

The issue is (and I am summarizing what was said years ago in this issue above) that Python runs a given Unicode string through `wcsxfrm` and then creates another Unicode string from the result. However, the result isn't Unicode (on any system, no matter the `wchar_t` encoding). It's a pretty random number that doesn't have to fit into the Unicode range. On Oracle Solaris, the implementation is such that the resulting values are very high. I believe that the reason it works on other platforms is IMHO pretty accidental (well, at least no standard enforces that, I think).

I do think (as was said already above) that the result from this function shouldn't be Unicode and shouldn't even be e.g. printable. However, I do realize that for backward compatibility reasons and considering that it works everywhere else, it's not a high priority to change this now.

Now, reading the old comments once more, it seems that what was originally rejected was the change from Python string to something else, but not necessarily the idea of splitting big values into two smaller ones. So maybe that can get it (we can enclose it in define guards if deemed necessary / too risky)? We have been using [this](https://github.com/oracle/solaris-userland/blob/master/components/python/python311/patches/24-strxfrm-fix.patch) for years now and didn't see any issues.

One last note - Solaris forks rewrote locale implementation, and e.g. on SmartOS, this is not an issue.

**Comment by kulikjak** [comment]
Sure, I just wanted to add some info for posterity should anybody be interested in why it still doesn't work as expected.

**Comment by serhiy-storchaka** [comment]
The original issue was not actually fixed. See also duplicate issue #138247.

There are two bugs here. First, that `wchar_t` codes in the result of `wcsxfrm()` are not Unicode code points. They can exceed the range 0-0x10ffff. Second, that `PyUnicode_FromWideChar()` can change order (for surrogate pairs on platform with 16-bit `wchar_t`, and on Solaris and other platforms with non-Unicode `wchar_t`).

#138242 fixes both bugs. Codes larger than 16-bit are split in two parts which preserve order, and `PyUnicode_FromKindAndData()` is used to convert an array of up to 17-bit integers to Python Unicode object. The type of the result is preserved. If all codes are less than 0x10000 and there are no surrogate pairs, the value is the same as before, so this change will have minimal impact even on programs that have wrong assumption about `locale.strxfrm()`.

**Comment by serhiy-storchaka** [comment]
Here results of some microbenchmarks. The first line is unpatched code, the second line is patched code.

```console
$ ./python -m timeit -s "import locale; locale.setlocale(locale.LC_ALL, 'en_US.UTF-8'); s = 'a'*10" "locale.strxfrm(s)"
500000 loops, best of 5: 571 nsec per loop
500000 loops, best of 5: 558 nsec per loop

$ ./python -m timeit -s "import locale; locale.setlocale(locale.LC_ALL, 'en_US.UTF-8'); s = 'à'*10" "locale.strxfrm(s)"
500000 loops, best of 5: 608 nsec per loop
500000 loops, best of 5: 566 nsec per loop

$ ./python -m timeit -s "import locale; locale.setlocale(locale.LC_ALL, 'en_US.UTF-8'); s = '\u9e02'*10" "locale.strxfrm(s)"
500000 loops, best of 5: 476 nsec per loop
500000 loops, best of 5: 475 nsec per loop

$ ./python -m timeit -s "import locale; locale.setlocale(locale.LC_ALL, 'en_US.UTF-8'); s = 'a'*1000" "locale.strxfrm(s)"
5000 loops, best of 5: 40.9 usec per loop
10000 loops, best of 5: 37.3 usec per loop

$ ./python -m timeit -s "import locale; locale.setlocale(locale.LC_ALL, 'en_US.UTF-8'); s = 'à'*1000" "locale.strxfrm(s)"
5000 loops, best of 5: 44.3 usec per loop
5000 loops, best of 5: 39.6 usec per loop

$ ./python -m timeit -s "import locale; locale.setlocale(locale.LC_ALL, 'en_US.UTF-8'); s = '\u9e02'*1000" "locale.strxfrm(s)"
10000 loops, best of 5: 31.2 usec per loop
10000 loops, best of 5: 30.6 usec per loop
```

You can see that there is no significant overhead, but there is a small speed up (up to 10%).
