### ISSUE TITLE
urllib does not support NO_PROXY environment variable containing domain with asterisk

### ISSUE THREAD

**Issue by f23e5a58-f4dd-406f-8e0f-07112c209812** [python/cpython#74647]
BPO | [30462](https://bugs.python.org/issue30462)
--- | :---
Nosy | @zhangyangyu, @csabella, @jirihnidek
PRs | <li>python/cpython#1795</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-05-24.20:13:11.639>
labels = ['type-feature', 'library', '3.10']
title = 'urllib does not support NO_PROXY environment variable containing domain with asterisk'
updated_at = <Date 2020-05-27.11:55:12.022>
user = 'https://github.com/jirihnidek'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-27.11:55:12.022>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-05-24.20:13:11.639>
creator = 'Jiri Hnidek'
dependencies = []
files = []
hgrepos = []
issue_num = 30462
keywords = []
message_count = 7.0
messages = ['294388', '294955', '295213', '296692', '297159', '320020', '370065']
nosy_count = 3.0
nosy_names = ['xiang.zhang', 'cheryl.sabella', 'Jiri Hnidek']
pr_nums = ['1795']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30462'
versions = ['Python 3.10']
```

</p></details>

**Comment by f23e5a58-f4dd-406f-8e0f-07112c209812** [comment]
Module urllib contains method proxy_bypass_environment(domain_name). This method check if domain_name should be excluded from proxying. The domain_name is checked against environment variable no_proxy or NO_PROXY. This variable contains comma separated list of domain names/domains. Domains can be specified in following variants:

 - domain.com
 - .domain.com
 - \*.domain.com

Method proxy_bypass_environment support first two variants, but it doesn't support variant with asterisk at beginning of domain. The last variant is not anything unusual; e.g.: https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

**Comment by zhangyangyu** [comment]
Hi Jiri, thanks for your PR. But at least we need a corresponding test and an entry in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) to complete the patch. Also, if your name is not in [Misc/ACKS](https://github.com/python/cpython/blob/main/Misc/ACKS), please add it. :-)

**Comment by f23e5a58-f4dd-406f-8e0f-07112c209812** [comment]
Hi Xiang,
* I added entry to [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS)
* I added my name to [Misc/ACKS](https://github.com/python/cpython/blob/main/Misc/ACKS) (without diacritics)
* I added/updated several unit tests
* I updated PR (two commits squashed into one commit)

Cheers,

Jiri

**Comment by zhangyangyu** [comment]
One question about this function: hosts like "\*.foo.com" gets an unambiguous intention, but how about hosts like "\*foo.com"? Should it match hosts like barfoo.com, or treat it as a typo and not match? Although the link says "asterisks can be used as wildcards" but I am still not quite sure it's intention.

**Comment by f23e5a58-f4dd-406f-8e0f-07112c209812** [comment]
Hi,
good point about \*foo.com. It seems this is not valid DNS RR according following RFC:

https://tools.ietf.org/html/rfc4592

Especially this section is more focused on allowed combinations of asterisks and other characters:

https://tools.ietf.org/html/rfc4592#section-2.1.1

There is also page at mediawiki about wildcards in DNS:

https://en.wikipedia.org/wiki/Wildcard_DNS_record

Thus I will modify my PR.
