### ISSUE TITLE
asyncio crashes when tearing down the proactor event loop

### ISSUE THREAD

**Issue by bc2cd49a-2dcc-436a-86bb-6178c73b723b** [python/cpython#83413]
BPO | [39232](https://bugs.python.org/issue39232)
--- | :---
Nosy | @asvetlov, @cjrh, @1st1, @zooba, @cmeyer, @mikeshardmind, @jack1142, @pepoluan
Files | <li>[example.py](https://bugs.python.org/file48829/example.py "Uploaded as text/plain at 2020-01-06.18:29:19 by @mikeshardmind"): toy code demonstrating the difference.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-06.18:29:20.714>
labels = ['3.10', '3.8', '3.9', 'type-crash', 'expert-asyncio']
title = 'asyncio crashes when tearing down the proactor event loop'
updated_at = <Date 2021-08-23.12:27:41.034>
user = 'https://github.com/mikeshardmind'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-23.12:27:41.034>
actor = 'machine.gw'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-01-06.18:29:20.714>
creator = 'mikeshardmind'
dependencies = []
files = ['48829']
hgrepos = []
issue_num = 39232
keywords = []
message_count = 7.0
messages = ['359448', '359515', '362174', '367932', '392261', '396339', '400132']
nosy_count = 11.0
nosy_names = ['asvetlov', 'cjrh', 'yselivanov', 'steve.dower', 'cmeyer', 'mikeshardmind', 'jack1142', 'rmawatson', 'pepoluan', 'lawsonjl.ornl', 'machine.gw']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue39232'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by zooba** [comment]
> eliminating the call to the event loop in __del__ would be even better. I understand that's easier said than done, or else ProactorBasePipeTransport wouldn't be leaning on __del__ in the first place.

This seems like a great idea, but I have no idea how feasible it is.

Do we have any active experts in asyncio who can make a judgement call on this? Suppressing the error in `__del__` seems like the safer option, but it also looks like it's only called from `__del__`, so maybe that's not the right idea.

**Comment by arhadthedev** [comment]
@zooba I have a PR fixing this (gh-92842).

**Comment by vstinner** [comment]
> maybe he can remember whether proactor and selector loops having different self.close() vs self._sock.close() calls was intentional?

I don't recall the rationale, if there was a rationale :-) The code has a long history coming from the tulip project. It even supported Python 3.3 and older.

When you're in ``__del__()``, the world is burning, maybe it's not a good idea to still schedule future callbacks by calling ``self.close()`` which calls ``self._loop.call_soon(self._call_connection_lost, None)`` whereas ``self`` is "being destroyed" (in fact, the GC is more complex than it, an object can "resurrect"). That's likely why I didn't call ``self.close()`` but ``self._sock.close()`` (in the selector implementation): the end of the ``self.close()`` -> ``self._call_connection_lost()`` callback chain.

Doing the same in proactor_events.py makes sense. For me, the only important part is to log the ResourceWarning to make sure that people don't get into this code path but close explicitly their asyncio transports. Relying on the GC to close transports, for making asynchronous code reliable is... a bad idea. In asyncio, close() **is** asynchronous and transports have a ``is_closing()`` method!

**Comment by zooba** [comment]
> When you're in `__del__()`, the world is burning, maybe it's not a good idea to still schedule future callbacks by calling `self.close()`

Okay, if we both agree on that part, let's take the fix for 3.11 and see whether the world breaks.

I think it should go to 3.10, but without anyone claiming to fully understand it, I'd rather get some real world experience in 3.11 beta before backporting to a stable release.

**Comment by mikeshardmind** [comment]
I can confirm the PR fixes the issue as I originally described.

I still think that relying on `__del__` here is not necessarily a good thing, but in the absence of expert opinion in the discussion at the time about removing that, I didn't bother to look much further into it and just ensured all transports in my code were closed before leaving scope (side-stepping the issue in my own code, rather than fixing it as a whole.)

**Comment by arhadthedev** [comment]
This issue may be closed because the bug is fixed:

- gh-92841

**Comment by spyoungtech** [comment]
I'm running into a similar (but principly the same issue) when using `asyncio.subprocess` with pipes that are open when the script exits. If this belongs in a separate issue, let me know.

As a simple example using a `IsolatedAsyncioTestCase` and `pytest`

```python
import asyncio
from asyncio.subprocess import create_subprocess_exec
from unittest import IsolatedAsyncioTestCase
import subprocess

class Test83413(IsolatedAsyncioTestCase):

    async def asyncSetUp(self) -> None:
        self.p = await create_subprocess_exec('notepad', stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        # This will cause an error because we're not cleaning up the open pipes

    async def test_simple(self):
        await asyncio.sleep(1)
        assert True is False
```

**Behaviors observed:**

<details>
<summary>Exception in 3.11.0b5 running `pytest`</summary>

```python
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000002BE556D0720>
Traceback (most recent call last):
  File "C:\Program Files\Python311b5\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311b5\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311b5\Lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311b5\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```
</details>

<details>
<summary>In 3.9.0 running `pytest`</summary>

```python
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000022937622280>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022937627A60>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python39\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python39\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022937627A60>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python39\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python39\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022937627A60>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python39\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python39\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```
</details>

**Expected (my preferred) behavior** is the simple warning that the process is being killed (the same as when no `stdin`/`stdout`/`stderr` arguments are provided):

```
Close running child process: kill <_WindowsSubprocessTransport closed pid=23660 running>
```

Reasonable (or more knowledgable) people could disagree on whether that's expected or not, but it would make reading my test outputs _much_ easier :)

**Comment by arhadthedev** [comment]
> If this belongs in a separate issue, let me know.

Did you run the test on Linux or macOS?

I cannot reproduce it on Windows 10. If you used non-Windows platform that we can be sure that this is caused not by `proactor_events.py` (covered by this issue) but by something else (so a new PR would be suitable).

Just for the record, here's my output for a clean build of 0771d71eea30316020a86b0eec071feb6d82d350 (labeled as `v3.11.0b5`):

```plain
C:\Users\oleg\Documents\dev\notmine\cpython>python test83413.py
Running Release|x64 interpreter...

C:\Users\oleg\Documents\dev\notmine\cpython>python --version
Running Release|x64 interpreter...
Python 3.11.0b5
```

**Comment by ashrobertsdragon** [comment]
This bug is still happening. People are getting it when using the MCP clients on Windows. [[
Proactor Windows warning on cleanup when using stdio_client](https://github.com/modelcontextprotocol/python-sdk/issues/391)](url)
Example (from aforemention git repo:
```py
import asyncio

from mcp import ClientSession, StdioServerParameters, stdio_client


async def main():
    server_params = StdioServerParameters(
        command="npx", args=["-y", "@playwright/mcp@latest"]
    ) # Or any other server

    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            print(await session.list_tools())
            await asyncio.sleep(2.0)


if __name__ == "__main__":
    asyncio.run(main())
```
Example traceback:
```sh
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001E2396C7CE0>
Traceback (most recent call last):
  File "C:\Users\ashro\AppData\Roaming\uv\python\cpython-3.13.2-windows-x86_64-none\Lib\asyncio\base_subprocess.py", line 129, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Users\ashro\AppData\Roaming\uv\python\cpython-3.13.2-windows-x86_64-none\Lib\asyncio\base_subprocess.py", line 81, in __repr__
    info.append(f'stdout={stdout.pipe}')
  File "C:\Users\ashro\AppData\Roaming\uv\python\cpython-3.13.2-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Users\ashro\AppData\Roaming\uv\python\cpython-3.13.2-windows-x86_64-none\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```
