### ISSUE TITLE
python-3.10.8-amd64.exe fails with Access is denied

### ISSUE THREAD

**Issue by cgohlke** [python/cpython#98193]
# Bug report

Installing `python-3.10.8-amd64.exe` on Windows 10 with options "Download debugging symbols" or "Download debug binaries" fails with "0x80070005 - Access is denied".

From the log file:
```
Error 0x80070005: Failed attempt to download URL: 'https://www.python.org/ftp/python/3.10.8/amd64/core_pdb.msi' to: 'C:\Windows\Temp\{D26D4A1A-A11A-4780-B3E9-B3EFD2A17C89}\core_JustForMe_pdb'
```

Opening `https://www.python.org/ftp/python/3.10.8/amd64/` currently returns `403 Forbidden`.

Also, the release page at https://www.python.org/downloads/release/python-3108/ does not currently list a download link for `python-3.10.8.exe` (32-bit).

# Your environment

- CPython versions tested on: python-3.10.8-amd64
- Operating system and architecture: Windows 10

**Comment by Molkree** [comment]
Not only it fails, but I'm also pretty sure it corrupts the previous install.

I had 3.10.7 installed prior to running the 3.10.8 installer, so I chose "Upgrade Now" (this should just upgrade the existing installation). After getting this Access is denied failure during the update, `py -V` or any other command doesn't return anything.

After manually going to my install folder and trying to run `python.exe` I'm getting this error:

![image](https://user-images.githubusercontent.com/12860284/195198633-30806d34-3546-4724-b93a-f3c55fc3e275.png)

**Comment by fredless** [comment]
given that it seems to be a current problem with the referenced download no surprise, but same issue encountered on win11

**Comment by AlexWaygood** [comment]
Cc. @zooba

**Comment by bersbersbers** [comment]
Similarly, `python-3.10.8-amd64.exe /layout .` fails as it cannot download https://www.python.org/ftp/python/3.10.8/amd64/ucrt.msi (while https://www.python.org/ftp/python/3.10.7/amd64/ucrt.msi exists):

![image](https://user-images.githubusercontent.com/12128514/195308277-dda1d0ad-6681-427a-82c3-9497a7563414.png)

**Comment by SekiBetu** [comment]
same here

**Comment by DimitryAndric** [comment]
Yep, same here. It's due to to the non-default option to download debug symbols during installation. (Note this is the "off-line" installer, it still needs to download the symbols, as otherwise the installer would become pretty large for all users, even though most of them will never need these.)

The problem should most likely be fixed by the web server administrators, who can allow read access to the https://www.python.org/ftp/python/3.10.8/amd64/ directory, similar to https://www.python.org/ftp/python/3.10.7/amd64/ (which *is* readable).

**Comment by ned-deily** [comment]
The permissions should be correct now. Please verify!

**Comment by cgohlke** [comment]
> The permissions should be correct now. Please verify!

Thank you! `python-3.10.8-amd64.exe` works now.


The download link for `python-3.10.8.exe` (32-bit) is still missing at https://www.python.org/downloads/release/python-3108/.

**Comment by pablogsal** [comment]
I think I managed to fix it, please check that works on your side. I also cleared the cache so new files/downloads should be there. I also refreshed the sigstore certs.

I'm closing the issue, feel free to reopen if we missed anything

**Comment by DimitryAndric** [comment]
Successfully completed installation with debug symbols now, on Windows amd64, using `python-3.10.8-amd64.exe`. Thanks!
